### PR TITLE
About us page added

### LINKED ISSUE #41: About Us page
## Description
Add About us page and write all the necessary things about  Catalyst organization. Keep it simple like in `Mock`.

## Mocks
about us
## Definition of Done
- [x] All of the required items are completed.
- [x] Approval by 1 mentor.

### PR DESCRIPTION
**Pull request by Bindusar1212**
Description
About us page added with linkedin icon in footer  

Fixes #41 

 Type of Change:
- Code
- Quality Assurance
- User Interface

Checklist:
- My PR follows the style guidelines of this project
-  I have performed a self-review of my own code or materials

-  I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by anubhavsingh16** [comment]
@aashimgarg please have a look.

**Comment by aashimgarg** [comment]
@Bindusar1212 you can do the following changes:-
1. reduce the space between the op of the age and the heading.
2. change the font.
(take reference from the month page).

**Comment by Bindusar1212** [comment]
@aashimgarg check this...Is it gud??

**Comment by aashimgarg** [comment]
> @aashimgarg check this...Is it gud??

its good but try to to keep the font uniform throughout the page!

**Comment by Bindusar1212** [comment]
@aashimgarg check this

**Pull request closed without merging**
