### PR TITLE
Added the screenshots to readme

### PR DESCRIPTION
**Pull request by vinayaksh42**

### CODE REVIEW

**Comment by anubhavsingh16** [comment]
@vinayaksh42 screenshots are absent and use the link of screenshot if possible.
by just uploading screenshot in `Attach files by dragging` you get the link.

vinayak

**Comment by anubhavsingh16** [comment]
before sending PR for Readme changes, check your changes from Preview option.

**Comment by vinayaksh42** [comment]
> before sending PR for Readme changes, check your changes from Preview option.

sir we can do the drag and drop method, but by doing that we will be depending on the github server for it. As we drag and drop a image over the comment section it basically uploads it over to the github server. So for avoiding that i made a pr which had a folder named "screenshot". It has the screenshots and we can easily call those images into our readme.md using the below command:-

hackathons and open source events


Timeline view of all the events


This works on the same concept but instead of using the github server we take photos from within our repo

**Pull request closed without merging**
